{extends $layout}
{block #content}

Usage: perform.php ACTION [OPTIONS]

Possible actions:
    default or no action	show this help
    syncdb			generate SQL code to synchronize database with model definition
    sqlall			generate SQL code of whole model definition
    sqlclear			generate SQL code to drop database structure
    sqlset			put modelset info into storage, no SQL code is created

    
Possible options:
    --confirm			confirms action as syncsql or sqlclear and executes code


{/block}
